### ISSUE TITLE
show the actuals values defined in enum?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#11]
``` r
library(ospsuite.utils)
Symbol <- enum(c(Diamond = 1, Triangle = 2, Circle = 2))
validateEnumValue(4, Symbol)
#> Error in validateEnumValue(4, Symbol): Value '' is not in defined enumeration values: 'Diamond, Triangle, Circle'.
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
So the error would be something like:

```r
#> Error in validateEnumValue(4, Symbol): Value is not in defined enumeration values: '1, 2'.
```

**Comment by msevestre** [comment]
The goal of enum is to NOT use magic number such as 1, 2 etc..
So the error message should be in this case
Error in validateEnumValue(4, Symbol): Value '4' is not in defined enumeration values: 'Diamond, Triangle, Circle'.

`Error in validateEnumValue(4, Symbol): Specified value is not in defined enumeration values: '1, 2'.`

defeats the purpose because we are exposing the internal values (1, 2 etc) instead of their enum counterpart.

**Comment by msevestre** [comment]
and yes
`Error in validateEnumValue("Square", Symbol): Value '' is not in defined enumeration values: 'Diamond, Triangle, Circle'.`

is also not behaving correctly :)

**Comment by IndrajeetPatil** [comment]
``` r
library(ospsuite.utils)
Symbol <- enum(c(Diamond = 1, Triangle = 2, Circle = 2))
validateEnumValue(4, Symbol)
#> Error in validateEnumValue(4, Symbol): Value '4' is not in defined enumeration values: 'Diamond, Triangle, Circle'.
```

<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
