### ISSUE TITLE
Add package global settings

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#68]

**Comment by IndrajeetPatil** [comment]
Which of these you are thinking of including in the utils package's global settings?

``` r
rlang::env_print(ospsuite:::ospsuiteEnv)
#> <environment: 0x000000002261b1a0>
#> Parent: <environment: empty>
#> Bindings:
#> * sensitivityAnalysisConfig: <named list>
#> * dimensionTask: <cobjRef>
#> * packageName: <chr>
#> * suiteName: <chr>
#> * pathSeparator: <chr>
#> * isPKSimLoaded: <lgl>
#> * suiteVersion: <chr>
#> * sensitivityAnalysis: <env>
#> * muSymbol: <chr>
#> * loadedSimulationsCache: <Cache>
#> * formatNumericsSmall: <dbl>
#> * formatNumericsDigits: <dbl>
#> * numberOfCores: <fn>
#> * containerTask: <NULL>
#> * showProgress: <lgl>
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
Doing it right now

**Comment by IndrajeetPatil** [comment]
Having looked at the PR, I want to go back to the basic question of why we need this in the first place.

We are adding complexity to the package architecture by introducing global settings, and it would be worth outlining here what the benefits are for paying this cost.

**Comment by msevestre** [comment]
The idea of settings in core was to have a place where we could define settings without polluting the default environment. Looking at packages like ggplot, we found that they define global settings 

I consider any number that is not a 0 a magic number. So the default number of digital (2 or 5) should definitely not be hard coded IMO. The idea of the settings is also for the user to be able to override the default... So that by setting number to 4, you will not need to change your code. 

Some.or those settings, such as path separator etc..are more read-only by nature.

I also see a need to have all strings (error, warning etc.. centralized). Not necessarily in one package or one file, but in files where you can easily find them. It helps to ensure that the language is written in a way that is consistent. It also avoids typos repetition by having a centralized place where the text is defined. We have started to define strings in the code lately and I think this could be also improved

As for settings, I would not aim to move all strings into one file. Package specific errors should be in the package. I think it's also ok to have some repetition if need be

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/commit/1f029a9f408095be4a286deeefe59195e68954f3
